#! /bin/sh

# Autostarts
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom --config "$HOME"/.config/picom/picom.conf &
flameshot &
xsetroot -cursor_name left_ptr &
~/.config/polybar/./launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &
pkill xautolock
xautolock -time 5 -locker "betterlockscreen -l" -notify 30 -notifier "notify-send 'Locker' 'Locking screen in 30 seconds'" -killtime 5 -killer "systemctl suspend" &

bspc monitor -d I II III IV

#bspc monitor DP-0 -d 2 3 4 5
#bspc monitor HDMI-0 -d 1

#if [ -x $HOME/bin/own_script_bspwm_laptop_dual_monitor ];then
#    own_script_bspwm_laptop_dual_monitor
#fi

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a virtualbox state=floating
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill ~/.config/wallpapers/old.jpg

#bspwm colores
#bspc config normal_border_color         "#51576d"
#bspc config active_border_color         "#babbf1"
#bspc config focused_border_color        "#babbf1"
#bspc config presel_feedback_color       "#babbf1"
#bspc config urgent_border_color         "#babbf1"
